// <auto-generated />
namespace EASY_KRK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class dodanie_profilu_i_poziomu_do_kierunku : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodanie_profilu_i_poziomu_do_kierunku));
        
        string IMigrationMetadata.Id
        {
            get { return "201512102005525_dodanie_profilu_i_poziomu_do_kierunku"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
