// <auto-generated />
namespace EASY_KRK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class longer_KEKMEK_description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(longer_KEKMEK_description));
        
        string IMigrationMetadata.Id
        {
            get { return "201512102259483_longer_KEKMEK_description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
