// <auto-generated />
namespace EASY_KRK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class poziom_profil_wymagane : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(poziom_profil_wymagane));
        
        string IMigrationMetadata.Id
        {
            get { return "201512102008467_poziom_profil_wymagane"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
