// <auto-generated />
namespace EASY_KRK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class float_to_double : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(float_to_double));
        
        string IMigrationMetadata.Id
        {
            get { return "201601061501099_float_to_double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
