// <auto-generated />
namespace EASY_KRK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class grupa_kursow_ECTS_BK_P : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(grupa_kursow_ECTS_BK_P));
        
        string IMigrationMetadata.Id
        {
            get { return "201601052128511_grupa_kursow_ECTS_BK_P"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
