//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EASY_KRK.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EASY_KRK.App_GlobalResources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria:.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPS:.
        /// </summary>
        public static string CNPS {
            get {
                return ResourceManager.GetString("CNPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPS musi być większe od 0..
        /// </summary>
        public static string CNPSAmountError {
            get {
                return ResourceManager.GetString("CNPSAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod przedmiotu nie może być pusty..
        /// </summary>
        public static string CodeErrorEmpty {
            get {
                return ResourceManager.GetString("CodeErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod przedmiotu może zawierać tylko znaki alfanumeryczne..
        /// </summary>
        public static string CodeErrorExpression {
            get {
                return ResourceManager.GetString("CodeErrorExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod przedmiotu musi zawierać od 3 do 15 znaków..
        /// </summary>
        public static string CodeErrorLength {
            get {
                return ResourceManager.GetString("CodeErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod kursu:.
        /// </summary>
        public static string CourseCode {
            get {
                return ResourceManager.GetString("CourseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkty ECTS:.
        /// </summary>
        public static string CourseECTS {
            get {
                return ResourceManager.GetString("CourseECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma zajęć:.
        /// </summary>
        public static string CourseForm {
            get {
                return ResourceManager.GetString("CourseForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktyczny?.
        /// </summary>
        public static string CoursePractical {
            get {
                return ResourceManager.GetString("CoursePractical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba punktów ECTS musi być większa od 0..
        /// </summary>
        public static string ECTSAmountError {
            get {
                return ResourceManager.GetString("ECTSAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkty ECTS (BK):.
        /// </summary>
        public static string ECTSBK {
            get {
                return ResourceManager.GetString("ECTSBK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba punktów ECTS_BK musi być większa lub równa 0..
        /// </summary>
        public static string ECTSBKAmountError {
            get {
                return ResourceManager.GetString("ECTSBKAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba punktów ECTS_BK nie może przekraczać całkowitej liczby ECTS..
        /// </summary>
        public static string ECTSBKECTSAmountError {
            get {
                return ResourceManager.GetString("ECTSBKECTSAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkty ECTS (P):.
        /// </summary>
        public static string ECTSP {
            get {
                return ResourceManager.GetString("ECTSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba punktów ECTS_P musi być większa lub równa 0..
        /// </summary>
        public static string ECTSPAmountError {
            get {
                return ResourceManager.GetString("ECTSPAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba punktów ECTS_P nie może przekraczać całkowitej liczby ECTS..
        /// </summary>
        public static string ECTSPECTSAmountError {
            get {
                return ResourceManager.GetString("ECTSPECTSAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przedmiotu nie może być pusta..
        /// </summary>
        public static string NameErrorEmpty {
            get {
                return ResourceManager.GetString("NameErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przedmiotu może zawierać tylko cyfry lub litery alfabetu polskiego..
        /// </summary>
        public static string NameErrorExpression {
            get {
                return ResourceManager.GetString("NameErrorExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przedmiotu musi zawierać od 3 do 100 znaków..
        /// </summary>
        public static string NameErrorLength {
            get {
                return ResourceManager.GetString("NameErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma zaliczenia:.
        /// </summary>
        public static string PassForm {
            get {
                return ResourceManager.GetString("PassForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod przedmiotu: .
        /// </summary>
        public static string SubjectCode {
            get {
                return ResourceManager.GetString("SubjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedmiot o podanym kodzie już istnieje..
        /// </summary>
        public static string SubjectCodeExists {
            get {
                return ResourceManager.GetString("SubjectCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma:.
        /// </summary>
        public static string SubjectForm {
            get {
                return ResourceManager.GetString("SubjectForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj:.
        /// </summary>
        public static string SubjectKind {
            get {
                return ResourceManager.GetString("SubjectKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przedmiotu:.
        /// </summary>
        public static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedmiot o podanej nazwie już istnieje..
        /// </summary>
        public static string SubjectNameExists {
            get {
                return ResourceManager.GetString("SubjectNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ:.
        /// </summary>
        public static string SubjectType {
            get {
                return ResourceManager.GetString("SubjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogólnouczelniany?.
        /// </summary>
        public static string SubjectUni {
            get {
                return ResourceManager.GetString("SubjectUni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZZU:.
        /// </summary>
        public static string ZZU {
            get {
                return ResourceManager.GetString("ZZU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZZU musi być większe od 0..
        /// </summary>
        public static string ZZUAmountError {
            get {
                return ResourceManager.GetString("ZZUAmountError", resourceCulture);
            }
        }
    }
}
