//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EASY_KRK.Res.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod przedmiotu nie może być pusty..
        /// </summary>
        public static string CodeErrorEmpty {
            get {
                return ResourceManager.GetString("CodeErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod przedmiotu może zawierać tylko znaki alfanumeryczne..
        /// </summary>
        public static string CodeErrorExpression {
            get {
                return ResourceManager.GetString("CodeErrorExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod przedmiotu musi zawierać od 3 do 15 znaków..
        /// </summary>
        public static string CodeErrorLength {
            get {
                return ResourceManager.GetString("CodeErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przedmiotu nie może być pusta..
        /// </summary>
        public static string NameErrorEmpty {
            get {
                return ResourceManager.GetString("NameErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przedmiotu może zawierać tylko cyfry lub litery alfabetu polskiego..
        /// </summary>
        public static string NameErrorExpression {
            get {
                return ResourceManager.GetString("NameErrorExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przedmiotu musi zawierać od 3 do 100 znaków..
        /// </summary>
        public static string NameErrorLength {
            get {
                return ResourceManager.GetString("NameErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod przedmiotu: .
        /// </summary>
        public static string SubjectCode {
            get {
                return ResourceManager.GetString("SubjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedmiot o podanym kodzie już istnieje..
        /// </summary>
        public static string SubjectCodeExists {
            get {
                return ResourceManager.GetString("SubjectCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma:.
        /// </summary>
        public static string SubjectForm {
            get {
                return ResourceManager.GetString("SubjectForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj:.
        /// </summary>
        public static string SubjectKind {
            get {
                return ResourceManager.GetString("SubjectKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przedmiotu:.
        /// </summary>
        public static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedmiot o podanej nazwie już istnieje..
        /// </summary>
        public static string SubjectNameExists {
            get {
                return ResourceManager.GetString("SubjectNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ:.
        /// </summary>
        public static string SubjectType {
            get {
                return ResourceManager.GetString("SubjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogólnouczelniany?.
        /// </summary>
        public static string SubjectUni {
            get {
                return ResourceManager.GetString("SubjectUni", resourceCulture);
            }
        }
    }
}
